package com.orizon_poc.guiarestproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Beneficiario implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "numeroCarteira")
	private int numeroCarteira;
	@org.kie.api.definition.type.Label(value = "nomeBeneficiario")
	private int nomeBeneficiario;

	public Beneficiario() {
	}

	public int getNumeroCarteira() {
		return this.numeroCarteira;
	}

	public void setNumeroCarteira(int numeroCarteira) {
		this.numeroCarteira = numeroCarteira;
	}

	public int getNomeBeneficiario() {
		return this.nomeBeneficiario;
	}

	public void setNomeBeneficiario(int nomeBeneficiario) {
		this.nomeBeneficiario = nomeBeneficiario;
	}

	public Beneficiario(int numeroCarteira, int nomeBeneficiario) {
		this.numeroCarteira = numeroCarteira;
		this.nomeBeneficiario = nomeBeneficiario;
	}

}