package com.orizon_poc.guiarestproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProcedimentoRealizado implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "procedimento")
	private com.orizon_poc.guiarestproject.Procedimento procedimento;
	@org.kie.api.definition.type.Label(value = "quantidadeExecutada")
	private int quantidadeExecutada;

	public ProcedimentoRealizado() {
	}

	public com.orizon_poc.guiarestproject.Procedimento getProcedimento() {
		return this.procedimento;
	}

	public void setProcedimento(
			com.orizon_poc.guiarestproject.Procedimento procedimento) {
		this.procedimento = procedimento;
	}

	public int getQuantidadeExecutada() {
		return this.quantidadeExecutada;
	}

	public void setQuantidadeExecutada(int quantidadeExecutada) {
		this.quantidadeExecutada = quantidadeExecutada;
	}

	public ProcedimentoRealizado(
			com.orizon_poc.guiarestproject.Procedimento procedimento,
			int quantidadeExecutada) {
		this.procedimento = procedimento;
		this.quantidadeExecutada = quantidadeExecutada;
	}

}