package com.orizon_poc.guiarestproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Procedimento implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "codigoTabela")
	private int codigoTabela;
	@org.kie.api.definition.type.Label(value = "codigoProcedimento")
	private int codigoProcedimento;
	@org.kie.api.definition.type.Label(value = "descricaoProcedimento")
	private java.lang.String descricaoProcedimento;

	public Procedimento() {
	}

	public int getCodigoTabela() {
		return this.codigoTabela;
	}

	public void setCodigoTabela(int codigoTabela) {
		this.codigoTabela = codigoTabela;
	}

	public int getCodigoProcedimento() {
		return this.codigoProcedimento;
	}

	public void setCodigoProcedimento(int codigoProcedimento) {
		this.codigoProcedimento = codigoProcedimento;
	}

	public java.lang.String getDescricaoProcedimento() {
		return this.descricaoProcedimento;
	}

	public void setDescricaoProcedimento(java.lang.String descricaoProcedimento) {
		this.descricaoProcedimento = descricaoProcedimento;
	}

	public Procedimento(int codigoTabela, int codigoProcedimento,
			java.lang.String descricaoProcedimento) {
		this.codigoTabela = codigoTabela;
		this.codigoProcedimento = codigoProcedimento;
		this.descricaoProcedimento = descricaoProcedimento;
	}

}